import { Product, Order, Review } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Vintage Denim Jacket',
    price: 450000,
    category: 'Jackets',
    size: 'M',
    available_sizes: ['S', 'M', 'L'],
    condition: 9,
    description: 'Classic 90s denim jacket in excellent condition. Minimal wear, all buttons intact. Perfect for layering a casual or vintage-inspired outfit.',
    image: 'https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=600&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=600&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1565084888279-aca607ecce0c?w=600&auto=format&fit=crop',
    ],
    stock: 5,
    is_featured: true,
    is_best_seller: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Classic White Tee',
    price: 120000,
    category: 'T-Shirts',
    size: 'L',
    available_sizes: ['M', 'L', 'XL'],
    condition: 8,
    description: 'Simple, clean white t-shirt. Slightly worn but still in great shape. Fits true to size. A wardrobe essential.',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&auto=format&fit=crop'],
    stock: 10,
    is_featured: true,
    is_best_seller: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Cozy Knit Sweater',
    price: 280000,
    category: 'Sweaters',
    size: 'S',
    available_sizes: ['XS', 'S', 'M'],
    condition: 9,
    description: 'Soft beige knit sweater, warm and comfortable. Barely worn with no pills. Great for fall and winter.',
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&auto=format&fit=crop'],
    stock: 3,
    is_featured: true,
    is_best_seller: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Streetwear Hoodie',
    price: 350000,
    category: 'Hoodies',
    size: 'XL',
    available_sizes: ['L', 'XL'],
    condition: 8,
    description: 'Urban streetwear hoodie with a relaxed fit. Front kangaroo pocket, drawstring hood. Light fading gives it that authentic vintage look.',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&auto=format&fit=crop'],
    stock: 4,
    is_featured: true,
    is_best_seller: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Retro 70s Shirt',
    price: 220000,
    category: 'Vintage Clothing',
    size: 'M',
    available_sizes: ['S', 'M'],
    condition: 7,
    description: 'Funky 70s-inspired collared shirt with a bold pattern. Authentic vintage piece from the era. Some light fading.',
    image: 'https://images.unsplash.com/photo-1618886614638-80e3c103d31a?w=600&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1618886614638-80e3c103d31a?w=600&auto=format&fit=crop'],
    stock: 2,
    is_featured: false,
    is_best_seller: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Slim Fit Jeans',
    price: 300000,
    category: 'Jeans',
    size: '32',
    available_sizes: ['30', '32', '34'],
    condition: 8,
    description: 'Dark wash slim fit jeans. Comfortable stretch denim. Light knee wear. Great everyday jeans.',
    image: 'https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=600&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=600&auto=format&fit=crop'],
    stock: 6,
    is_featured: false,
    is_best_seller: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Oversized Flannel Shirt',
    price: 180000,
    category: 'Vintage Clothing',
    size: 'L',
    available_sizes: ['M', 'L', 'XL'],
    condition: 8,
    description: 'Classic plaid flannel shirt in an oversized cut. Warm and stylish. Great for layering.',
    image: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=600&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=600&auto=format&fit=crop'],
    stock: 7,
    is_featured: false,
    is_best_seller: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Vintage Windbreaker',
    price: 400000,
    category: 'Jackets',
    size: 'S',
    available_sizes: ['XS', 'S'],
    condition: 9,
    description: '90s vintage windbreaker in excellent condition. Vibrant colors, full zip, elastic cuffs. A true era piece.',
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&auto=format&fit=crop'],
    stock: 2,
    is_featured: true,
    is_best_seller: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Band Graphic Tee',
    price: 150000,
    category: 'T-Shirts',
    size: 'M',
    available_sizes: ['S', 'M', 'L'],
    condition: 7,
    description: 'Vintage band graphic tee with faded print. Authentic wear adds to the charm. 100% cotton.',
    image: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=600&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=600&auto=format&fit=crop'],
    stock: 8,
    is_featured: false,
    is_best_seller: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Cargo Jogger Pants',
    price: 250000,
    category: 'Jeans',
    size: '30',
    available_sizes: ['28', '30', '32'],
    condition: 8,
    description: 'Relaxed cargo jogger pants with multiple pockets. Comfortable and functional streetwear.',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4bef28?w=600&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1594938298603-c8148c4bef28?w=600&auto=format&fit=crop'],
    stock: 5,
    is_featured: false,
    is_best_seller: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '11',
    name: 'Wool Blend Coat',
    price: 550000,
    category: 'Jackets',
    size: 'M',
    available_sizes: ['M'],
    condition: 9,
    description: 'Premium wool blend overcoat in charcoal grey. Barely worn, no damage. Classic silhouette that never goes out of style.',
    image: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600&auto=format&fit=crop'],
    stock: 1,
    is_featured: true,
    is_best_seller: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '12',
    name: 'Pullover Crewneck',
    price: 200000,
    category: 'Sweaters',
    size: 'XL',
    available_sizes: ['L', 'XL', 'XXL'],
    condition: 8,
    description: 'Simple crewneck pullover sweatshirt. Soft fleece interior, minimal branding. Great everyday wear.',
    image: 'https://images.unsplash.com/photo-1620799140188-3b2a02fd9a77?w=600&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1620799140188-3b2a02fd9a77?w=600&auto=format&fit=crop'],
    stock: 9,
    is_featured: false,
    is_best_seller: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    product_id: '1',
    user_name: 'Sarah K.',
    rating: 5,
    comment: 'Absolutely love this piece! The quality is amazing for the price. Will definitely shop here again.',
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r2',
    product_id: '1',
    user_name: 'James T.',
    rating: 4,
    comment: 'Great condition as described. Fast shipping too. Very happy with my purchase.',
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r3',
    product_id: '4',
    user_name: 'Aisha M.',
    rating: 5,
    comment: 'Perfect fit and exactly as described. Sustainable shopping at its best!',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r4',
    product_id: '2',
    user_name: 'Carlos R.',
    rating: 4,
    comment: 'Clean and comfortable. Good quality for a thrift piece.',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r5',
    product_id: '3',
    user_name: 'Mia L.',
    rating: 5,
    comment: 'This sweater is so cozy! Fits perfectly and looks great.',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'order-001',
    user_id: 'demo-user',
    customer_name: 'Demo User',
    customer_email: 'demo@example.com',
    customer_phone: '012-345-6789',
    shipping_address: '123 Main Street, Kuala Lumpur, 50000',
    payment_method: 'e_wallet',
    total_price: 570000,
    status: 'completed',
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    order_items: [
      {
        id: 'oi-1',
        order_id: 'order-001',
        product_id: '1',
        product_name: 'Vintage Denim Jacket',
        product_image: 'https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=600&auto=format&fit=crop',
        quantity: 1,
        price: 450000,
        size: 'M',
        created_at: new Date().toISOString(),
      },
      {
        id: 'oi-2',
        order_id: 'order-001',
        product_id: '2',
        product_name: 'Classic White Tee',
        product_image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&auto=format&fit=crop',
        quantity: 1,
        price: 120000,
        size: 'L',
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'order-002',
    user_id: 'demo-user',
    customer_name: 'Demo User',
    customer_email: 'demo@example.com',
    customer_phone: '012-345-6789',
    shipping_address: '123 Main Street, Kuala Lumpur, 50000',
    payment_method: 'bank_transfer',
    total_price: 350000,
    status: 'shipped',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    order_items: [
      {
        id: 'oi-3',
        order_id: 'order-002',
        product_id: '4',
        product_name: 'Streetwear Hoodie',
        product_image: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&auto=format&fit=crop',
        quantity: 1,
        price: 350000,
        size: 'XL',
        created_at: new Date().toISOString(),
      },
    ],
  },
];
